# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8e96943e42e064e5b9976d1efc1a497c"
name = "wishlist"
handle = "wishlist-408"
application_url = "https://marriott-essence-tapes-baby.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "aghori-theme-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://marriott-essence-tapes-baby.trycloudflare.com/auth/callback",
  "https://marriott-essence-tapes-baby.trycloudflare.com/auth/shopify/callback",
  "https://marriott-essence-tapes-baby.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
